### ISSUE TITLE
rename this repo

### ISSUE THREAD

**Issue by stevemart** [IBM/powerai-market-sentiment#17]
the repo name is too vague, how about powerai-financial-market-prediction?

**Comment by markstur** [comment]
@stevemart Is this gonna happen?  Close the issue?

**Comment by stevemart** [comment]
@markstur i think we still need to rename it, any suggestions?

**Comment by markstur** [comment]
@stevemart Your suggested name looks OK to me.  Maybe get sentiment in there with powerai-market-sentiment?  Either looks fine to me. Maybe ask the authors. @rhagarty @scottdangelo

**Comment by stevemart** [comment]
changed from powerai-notebook to powerai-market-sentiment
